"""added new fields to the each table, this is the final schema change before MVP deployment

Revision ID: 12ac05916086
Revises: f572fca92006
Create Date: 2026-04-16 15:23:45.455293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12ac05916086'
down_revision: Union[str, Sequence[str], None] = 'f572fca92006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queue_entries', sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_queue_entries_id'), 'queue_entries', ['id'], unique=False)
    op.add_column('queues', sa.Column('avg_serve_time', sa.Integer(), nullable=False))
    op.add_column('queues', sa.Column('scheduled_open_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('queues', sa.Column('scheduled_close_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('queues', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_queues_id'), 'queues', ['id'], unique=False)
    op.drop_column('queues', 'scheduled_start_at')
    op.drop_column('queues', 'rules')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.add_column('queues', sa.Column('rules', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('queues', sa.Column('scheduled_start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_queues_id'), table_name='queues')
    op.alter_column('queues', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('queues', 'scheduled_close_at')
    op.drop_column('queues', 'scheduled_open_at')
    op.drop_column('queues', 'avg_serve_time')
    op.drop_index(op.f('ix_queue_entries_id'), table_name='queue_entries')
    op.drop_column('queue_entries', 'joined_at')
    # ### end Alembic commands ###
